service: serverless-app
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-southeast-1
  environment:
    NODE_ENV: production
    # memorySize: 128
functions:
  app:
    handler: app.handler
    layers:
      - { Ref: CoreModulesLambdaLayer }
      - { Ref: OptionalModulesLambdaLayer }
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: false
    # includeModules:
    #   forceInclude:
    #     - aws-sdk

  prune:
    automatic: true
    number: 3

package:
  individually: true
  patterns:
      - '!node_modules/**'
    # - node_modules/**
    # - .git/**
    # - .vscode/**
    # - .DS_Store
    # - README.md
    # - test/**
    # - docs/**

layers:
  coreModules:
    path: layers/core
    compatibleRuntimes:
      - nodejs18.x
  optionalModules:
    path: layers/optional
    compatibleRuntimes:
      - nodejs18.x

# Add any custom environment variable file for serverless-dotenv-plugin
dotenv:
  path: .env


