service: lambda-app

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-southeast-1
  environment:
    NODE_ENV: production

functions:
  app:
    handler: server.handler
    fileSystemConfig:
      localMountPath: /mnt/lambda
      arn: arn:aws:elasticfilesystem:<...>:<accessPoint>
    vpc:
      securityGroupIds:
        - sg-...
      subnetIds:
        - subnet-...
        - subnet-...
        - subnet-...
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
          
plugins:
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: false

  prune:
    automatic: true
    number: 3


package:
  individually: true
  patterns:
      - '!node_modules/**'

# Add any custom environment variable file for serverless-dotenv-plugin
dotenv:
  path: .env
